spring:
  application:
    name: order-service
  datasource:
    # jdbc:mysql://${MYSQL_HOST:mysql-standalone}:3306/db_order
    url: jdbc:mysql://localhost:3306/db_order
    username: hoangtd5
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      # drop n create table, good for testing, comment this in production
      ddl-auto: update
      #`hibernate_sequence' doesn't exist
      use-new-id-generator-mappings: false
    # Show or not log for each sql query
    show-sql: true

server:
  port: 8093
