spring:
  application:
    name: product-service
  datasource:
    # jdbc:mysql://${MYSQL_HOST:mysql-standalone}:3306/db_product
    url: jdbc:mysql://mysql-standalone:3306/db_product?createDatabaseIfNotExits=true&useUnicode=yes&characterEncoding=utf8
    username: hoangtd5
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      # drop n create table, good for testing, comment this in production
      ddl-auto: update
      #`hibernate_sequence' doesn't exist
      use-new-id-generator-mappings: false
    # Show or not log for each sql query
    show-sql: true

# setting minio store file
storage:
  access-key: minio
  secret-key: minio123
  entpoint: http://172.20.0.3:9000/
  expire: 600
  bucketNamePrefix: tiger-

server:
  port: 8091